FROM python:3.11-slim

WORKDIR /locust

COPY locustfile.py /locust
COPY requeriments.txt /locust

RUN pip install --no-cache-dir -r requeriments.txt

EXPOSE 8089

CMD ["locust", "-f", "locustfile.py"]